FROM nginx:1.27-alpine

COPY render-default.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --retries=5 CMD wget -qO- http://localhost/health >/dev/null || exit 1
