spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketx_positions
    username: marketx
    password: marketx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
