spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketx_risk
    username: marketx
    password: marketx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

marketx:
  position-service:
    url: http://localhost:8081
  pnl-service:
    url: http://localhost:8082
